### ISSUE TITLE
Delete isn't working on django1.7

### ISSUE THREAD

**Issue by alonsogodinez** [05bit/brillixy#2]
Error  : /templates/admin/delete_selected_confirmation.html    in line 6 
i tried delete  line 5,6,7 and delete action works perfectly :D
anyway... what is that block for? :P.    PD: Thank you so much brillixy is helping me a lot in my college project :')

**Comment by Ryanb58** [comment]
Did this issue ever get resolved?

**Comment by rudyryk** [comment]
Hi @Ryanb58! Should work now, just updated release on PyPi.

As you can see I don't have much activity on this project. It would be good to cover project with tests and update it for upcoming Boostrap 4, but I'm lacking of time & resource, so I'm not sure about future of the project to be honest.

Thanks for your interest! :)
